spring.application.name=email-verifier
server.port=8080
# Enable Java 21 Virtual Threads for all incoming web requests
spring.threads.virtual.enabled=true
# for debugging network calls
logging.level.org.springframework.web=INFO